# coding: utf-8

"""
    1Password Partnership API

    Trusted by more than 100,000 businesses to protect their data, 1Password gives you complete control over passwords and other sensitive business information.   As an integral layer of the Identity and Access Management (IAM) stack, 1Password protects all employee accounts – even those you aren't aware of. Give employees secure access to any app or service and safely share everything you need to work together – including logins, documents, credit cards, and more – while keeping everything else private.  1Password is easy to deploy and integrates with Azure AD, Okta, OneLogin, and Slack, so you can automatically provision employees using the systems you already trust. It's simple to manage and fits seamlessly into your team's workflow, so you can secure your business without compromising productivity.

    The version of the OpenAPI document: 2.0.0
    Contact: partners@1password.com
    Created by: https://www.1password.partners/English/
"""

from 1_password_partnership_python_sdk.paths.api_v1_partners_accounts.post import BeginProvisioningProcess
from 1_password_partnership_python_sdk.paths.api_v1_partners_accounts_customer_account_uid.get import GetByUid
from 1_password_partnership_python_sdk.paths.api_v1_partners_accounts_customer_account_uid.delete import RemoveFromPartnership
from 1_password_partnership_python_sdk.paths.api_v1_partners_accounts_customer_account_uid.patch import UpdateEndsAtByUid
from 1_password_partnership_python_sdk.apis.tags.account_api_raw import AccountApiRaw


class AccountApi(
    BeginProvisioningProcess,
    GetByUid,
    RemoveFromPartnership,
    UpdateEndsAtByUid,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AccountApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AccountApiRaw(api_client)
